# version: "3.8"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_db
    environment:
      POSTGRES_DB: ${PGDATABASE:-rag}
      POSTGRES_USER: ${PGUSER:-rag}
      POSTGRES_PASSWORD: ${PGPASSWORD:-ragpw}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    build: ./api
    container_name: rag_api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app
      - ./data:/data
    ports:
      - "8000:8000"
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

volumes:
  pg_data:
